# Generated by Django 4.1.5 on 2023-01-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllJobsStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('averageSalary', models.DecimalField(decimal_places=2, max_digits=13)),
                ('vacanciesAmount', models.IntegerField()),
                ('SalaryImg', models.ImageField(upload_to='static/img/')),
            ],
        ),
        migrations.CreateModel(
            name='FullStackStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('averageSalary', models.DecimalField(decimal_places=2, max_digits=13)),
                ('vacanciesAmount', models.IntegerField()),
                ('SalaryImg', models.ImageField(upload_to='static/img/')),
            ],
        ),
    ]
