# Generated by Django 4.1.5 on 2023-01-14 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0002_statsimages_remove_alljobsstats_salaryimg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statsimages',
            old_name='AllImg',
            new_name='allImg',
        ),
        migrations.RenameField(
            model_name='statsimages',
            old_name='SullStackImg',
            new_name='fullStackImg',
        ),
    ]
